spring.application.name=work.user
server.port=8081
springdoc.swagger-ui.path=/swagger-ui

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/work_user
spring.datasource.username=postgres
spring.datasource.password=${DB_PG_PWD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

external.task.service.baseurl=http://localhost:8082